### ISSUE TITLE
Printing problem of collector

### ISSUE THREAD

**Issue by duncantl** [duncantl/RTypeInference#1]
The following function

``` r
isum =
function(x, n)
{
  total = 0
  for(i in 1:n)
      total = total + x[i]
  total
}
```

causes the collector to fail to print after inferring the types.

```
collector = TypeCollector()
inferTypes(isum, collector)
```

The output is

```
Error in getTypeID(object) :
  no slot of name "ref" for this object of class "VectorType"

Enter a frame number, or 0 to exit

1: function (object)
standardGeneric("show")(x)
2: function (object)
standardGeneric("show")(x)
3: cat("Type", names(getTypeID(object)), "\n")
4: getTypeID(object)
```

**Comment by nick-ulle** [comment]
This works correctly on the fork for

``` r
isum =
function(x, n)
{
  .typeInfo(x = VectorType(NumericType(), NA), n = IntegerType())
  total = 0
  for(i in 1:n)
      total = total + x[i]
  return(total)
}
```

**Comment by duncantl** [comment]
Thanks. 
Can you add the ability to specify the types in the call to inferTypes().  This example comes from where I am actually generating code for two different input types x as a integer and alternatively as a numeric vector. So I'd like to be able to specify the types w/o modifying the content of the function.

**Comment by nick-ulle** [comment]
Is a .typeInfo attribute on the function okay? This is working now:

``` r
isum =
function(x, n)
{
  total = 0
  for(i in 1:n)
    total = total + x[i]
  total
}

attr(isum, ".typeInfo") =
  list(x = VectorType(NumericType(), NA), n = IntegerType())
```

**Comment by duncantl** [comment]
It would be much more convenient and direct to to have a 
inferType(......., .typeInfo = list(.....))
rather than having to set the attribute and then remove it after the inferType() call.

**Comment by nick-ulle** [comment]
Done.
