### ISSUE TITLE
Inferring types of locals

### ISSUE THREAD

**Issue by duncantl** [duncantl/RTypeInference#2]
In the isum example again

``` r
isum =
function(x, n)
{
  total = 0
  for(i in 1:n)
      total = total + x[i]
  total
}
```

Can we get the type inference to recognize that, if x is VectorType(NumericType()), then total should be
numeric and not integer. 
The RLLVMCompile currently uses the heuristic that total would be an integer, but it doesn't look ahead.

**Comment by nick-ulle** [comment]
The fork already does this, because it recognizes that `x` is numeric, so `total + x[i]` will upcast to numeric.

**Comment by duncantl** [comment]
Great.
